### PR TITLE
Chinese Simp. translation (with README_CN.md)

### PR DESCRIPTION
**Pull request by ycwei982**
According to #25 mchorse said:

> oh, wait, I forgot one thing to do, the config comments are impossible to translate at the moment, so I'll have to write some code to make it possible. I'll let you know when I'll finish.

So I didn't apply `config.yml` translation, I kept it in English. I will apply translation when mchorse finished ASAP.

All files should be encoded in UTF-8.

### CODE REVIEW

**Comment by mchorse** [comment]
Wow, that's a lot of translation! Thanks!

Ok, I see that some of the strings are quite long, would it affect the size of the elements in GUI? I mean like, overflown strings in fixed sized buttons, you know?

Could you build the mod and test whether text labels aren't overflowing (if you think it's important)? I could build for you, but if you can do it youself, it preferably if you could do this.

**Comment by ycwei982** [comment]
I can build by myself and I made a clone video like your "How to make a machinima using Blockbuster mod", I haven't find something overflown at this period while I am recording videos. Now the video is encoding, I will upload to YouTube when encoding finished, then you can see effects.

**Comment by mchorse** [comment]
Oh, cool! 😄 

I'll try to extract comments from source code in the next few days. Do you want me to merge this pull request, and then you'll pull request again when I'll finish, or are ok with waiting a bit and then merging my code and add config comment translations?

**Comment by ycwei982** [comment]
It is up to you to decide.

I prefer merge this PR because I am going to share (or repost) this mod soon to Chinese Minecraft Forum and other social media blah. 

I think if I paste repository address as `mchorse/blockbuster` instead of `ycwei982/blockbuster`, there may be more contributors to help translate this...

**Comment by ycwei982** [comment]
[Chinese simple tutorial](https://youtu.be/nR1-QwPHJN4), you can see Chinese GUI here as well. Sorry it is plain Chinese, I added your YouTube link in the description

**Comment by mchorse** [comment]
Ok, so I'll merge now, and will let you know when I'll push translateable config comments. By the way, just wonder, are you going to destribute your own build, or you'll wait for me to publish multi-version builds on CurseForge?

**Comment by ycwei982** [comment]
I am now distributing my build with unofficial tag, when you made a new release I will delete my build then change download links to your CurseForge.

**Pull request merged**
