### PR TITLE
translate zh_CN and add a punctuation

### PR DESCRIPTION
**Pull request by ycwei982**
don't mind some 'blank' changes, that's something with Atom editor. And _gradle.properties_, i changed it for my proxy (you know China network 😂) and i may link translated wiki to my fork? i will translate soon

### CODE REVIEW

**Comment by mchorse** [comment]
> don't mind some 'blank' changes, that's something with Atom editor

It might be some feature that removes spaces/tabs from empty lines.

> gradle.properties

It doesn't seems to be present in the PR, do you mean it's in your fork?

>  and i may link translated wiki to my fork? i will translate soon

Yeah, sure but I still haven't updated wiki to `1.4.8` (it's wiki for Blockbuster `1.4.7` 😂). Would you wait for me to update it first? Or is it totally fine? I mean, it's fine with me, but it will be more work afterwards if you'll do it now.

**Comment by ycwei982** [comment]
> It doesn't seems to be present in the PR, do you mean it's in your fork?

it is just in my hard drive, i modified it when i was building, and then delete, so there was a useless diff of gradle.properties...

> Yeah, sure but I still haven't updated wiki to 1.4.8 (it's wiki for Blockbuster 1.4.7 😂). Would you wait for me to update it first? Or is it totally fine? I mean, it's fine with me, but it will be more work afterwards if you'll do it now.

I don't mind if i do it now, because i have lots of free time though, i just want to make a guide in Chinese and then they will not PM me too much 😂

**Comment by mchorse** [comment]
> it is just in my hard drive, i modified it when i was building, and then delete, so there was a useless diff of gradle.properties...

Oh, I see 😄 

> I don't mind if i do it now, because i have lots of free time though, i just want to make a guide in Chinese and then they will not PM me too much

Alright, then I'll update it before `1.4.9` will come out. I'll let you know 😃

**Comment by mchorse** [comment]
@ycwei982 new plan, I'm starting to remove camera code from the `dev` branch, and creating compatibility layer to Aperture mod, so for now, PR to `master` branch (sorry for confusion). I'll let you know when stuff is going to be finished.

**Comment by ycwei982** [comment]
Roger that
在 2017年6月26日 下午5:15，Sir McHorse <notifications@github.com>写道：

@ycwei982<https://github.com/ycwei982> new plan, I'm starting to remove camera code from the dev branch, and creating compatibility layer to Aperture mod, so for now, PR to master branch (sorry for confusion). I'll let you know when stuff is going to be finished.

―

**Pull request merged**
