### PR TITLE
Add support for materials in bedrock particles

### PR DESCRIPTION
**Pull request by l89669**

### CODE REVIEW

**Comment by Chryfi** [comment]
Thank you for contributing, I will review your PR.

**Comment by Chryfi** [comment]
You didn't change anything in the GUI, you need to add the new material to the GUI in GuiSnowstormGeneralSection and GuiSnowstormCollisionAppearanceSection. You also need to add a language key to /help/en_US/gui.yml.

**Comment by l89669** [comment]
Added new material selection in GUI per your request

**Comment by Chryfi** [comment]
Looks good, thank you for your contribution. You will be mentioned in the changelog.

**Pull request merged**
