### PR TITLE
README_CN.md small patches

### PR DESCRIPTION
**Pull request by ycwei982**
😂

### CODE REVIEW

**Comment by mchorse** [comment]
😂 👌

**Comment by mchorse** [comment]
By the way, @ycwei982, if you want to can use [reads](https://github.com/mchorse/reads) repository to store Chinese versions of the documents. I use this repository mainly for building my READMEs and change logs for different mod websites such as Curse (which uses HTML), MCForum (BBCode with paragraphs), PMC (BBCode) and GitHub (Markdown).

**Comment by ycwei982** [comment]
Actually when I copy READMEs from GitHub web reader, Chinese Minecraft Forum can fit that display format😂

**Comment by mchorse** [comment]
Oh, cool! 😀 

I prefer the raw text, so it won't had these margin artifacts *looks at MCForum* 😬

**Pull request merged**
