### PR TITLE
Can we get more models? Like halflings, dwarves, elves

### PR DESCRIPTION
**Pull request by koalaGP**
Please

### CODE REVIEW

**Comment by mchorse** [comment]
What is this? I mean, I clearly see you're pull requesting stuff from dev to be merged into master, but... I merge to master ONLY when the code is ready for release, but it's not ready for release.

About the actual matter, I'm not sure whether it feels natural to have those models in built-in in Blockbuster (because it only benefits people who are going to make Sci-Fi/Fantasy stuff). Do you realize that you can create those models yourself either using [in-game model editor](https://youtu.be/CoJ_6Byh6LA) or [web app model editor](https://youtu.be/V9n1xeIewN0)?

**Comment by ycwei982** [comment]
why there so 'much' commits...

**Comment by Poslovitch** [comment]
Cause he doesn't know the difference between an issue and a PR. Or he didn't searched enough to find the big "create an issue" button.

Basically, this PR is just the dev branch to master.

**Comment by mchorse** [comment]
Correct 😂 

Thus the reason why I should close it.

**Pull request closed without merging**
