### PR TITLE
Blockbuster particle system additions/changes

### PR DESCRIPTION
**Pull request by Chryfi**
List of additions:
 - local space section:
	- relative direction: it rotates the direction vector when spawning according to the rotation of the emitter/body part. 
	  Example: make particles shoot out of a body part like blood
	- relative acceleration: it rotates the acceleration vector throughout the whole lifetime of a particle according to the body 
	  part's local rotation.
	- gravity: this adds a y acceleration of -9.81 which won't be affected by the local acceleration
- appearance section:
	- camera facing mode button
 - collision section:
	- realistic collision: the direction vector will be mirrored on collision. Example: together with gravity particles can now 
	  bounce realistically like a bouncy rubber ball.
	- random direction: this randomizes the direction on collision. It can be used with realistic collision on or off. It doesn't 
	  affect the speed, it only changes the direction. When bounciness is zero this still changes the direction just without
	  reflecting on the surface. This could be used for force fields.
		- preserve energy: when bounciness=0 and random bounciness!=0 - an enabled preserve energy would ignore that the vector component responsible for colliding will be zero. Enabled preserve energy will make the particles fast.
	- split particles: this splits the particles into a given amount on impact. Their speed will change according to the number of 
	  splits e.g. 4 splits => speed/4
	- split particles speed threshold: this is the speed threshold for activating the split process.
	- damping: reduce the velocity of the particles on impact. Valid range 0 - 1, 1 being the highest damping (1 reduces the 
	  velocity completely)
	- random damping: randomize the damping. Values are 0 - 1. Example: damping of 1.0 and random damping of 0.5 means the damping will vary between 0.5 and 1.5
	- change texture/appearance on collision
	- change tint and lighting on collision
	- expire on impact delay: would be also useful for texture on impact - can be used with Molang Expressions like math.random - negative values will be turned into positive values
	- collision with entity's hitboxes
	- collision with entity pseudo momentum
		- Idea for the future: add multiple hitboxes to models in the model editor
		- Idea for the future: own hitbox so it can be rectangular - then it also needs to rotate
- MolangExpressions
	- added the variables "variable.particle_speed.length",  "variable.particle_speed.x", "variable.particle_speed.y" and "variable.particle_speed.z". Could be used for motionblur like effect.
	- added the variable (later by McHorse) "variable.particle_bounces": it counts how many times a particle bounced off a surface - doesn't count for ever when it's lying on a surface (one count for that situation).

Known bugs:
- _with realistic collision on: sometimes the particle bounces very slightly on the ground although it is clearly lying on the ground._ probably fixed now - fixed original code: particles now reposition correctly with high radius

### CODE REVIEW

**Comment by mchorse** [comment]
Thanks, great work! I'll accept it once I'll be modding, hopefully that's cool. 👍

**Comment by Chryfi** [comment]
Hopefully it is also cool that I might change minor little things as I programmed it at a fast pace. because I currently have a lot of other stuff to do. Oh and this weekend I will probably add another feature which might be really cool. Something that will require a little more than vector geometry ;).
Oh and please give me feedback about this compatibility issue so I can maybe start designing it the way it may be required. Is it allowed to add code to the Bedrock System like I did?

**Comment by mchorse** [comment]
Feel free adding them whatever way you want right now, I’ll refactor it later and you’ll be able to reflect upon it, alright?

**Comment by Chryfi** [comment]
Ok, let's do it so 👍

**Comment by mchorse** [comment]
Great job! Thank you very much for such rich feature extensions for particle system! 🥳

**Pull request merged**
