### PR TITLE
Me being a grammar nazi.

### PR DESCRIPTION
**Pull request by lvivtotoro**
I fixed a couple of spelling errors, sorry for being such a grammar nazi..

### CODE REVIEW

**Comment by mchorse** [comment]
Well, I actually like grammar nazis, thanks for not being afraid to be grammar nazi 😄

**Comment by lvivtotoro** [comment]
Will do!

**Comment by lvivtotoro** [comment]
Wait.. for spell checks.. or?

**Comment by mchorse** [comment]
> Wait.. for spell checks.. or?

Well, mostly for grammar :)

There are several files that contains text for users:

* `README.md`
* `MANUAL.md`
* `src/main/resources/assets/blockbuster/lang/en_US.lang`

Thank you very much :)

P.S.: "Usage: Usage: " thing I know about it, but I didn't noticed until I started recording the tutorial video (I almost finished with it, only two minutes left to voice over).

**Comment by lvivtotoro** [comment]
No problem!

**Comment by mchorse** [comment]
Nevermind about "Usage: Usage: " part. It looks like I fixed it, and then forgot to build and update my mod's `blockbuster-1.1.jar` 😄

**Pull request merged**
