### PR TITLE
Update Chinese Localization 1.6

### PR DESCRIPTION
**Pull request by ycwei982**

### CODE REVIEW

**Comment by mchorse** [comment]
Wow, that was quick, thank you very much! 😊👌

**Comment by ycwei982** [comment]
Don't forget the aperture one

**Comment by ycwei982** [comment]
Fine I don't know why my email notifications of aperture failed 😂

**Comment by mchorse** [comment]
They haven't failed, I just decided to check Twitter, and then I kind of got carried away 😂

**Pull request merged**
