### PR TITLE
Update "BB Gun" Chinese Localization

### PR DESCRIPTION
**Pull request by ycwei982**

### CODE REVIEW

**Comment by mchorse** [comment]
Thanks for translating the keys, but unfortunately, I haven't extracted GUI strings back then... could you please translate the remaining strings in `gui.yml`?

**Comment by ycwei982** [comment]
I will do it in 3 hours I think

**Comment by mchorse** [comment]
Thank you! 🙂👍

**Comment by ycwei982** [comment]
I think I finished it, and the question is that what exactly `accuracy` is.

In the dev build, it seems when the amount is larger, the less accurate it is. Because of this, I translated **accuracy** as **scatter** in Chinese.

**Pull request merged**
